/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.testing;



import java.awt.Font;

/**
 *
 * @author ACER
 */
public class AdvanceFont extends javax.swing.JFrame {

    /**
     * Creates new form AdvanceFont
     */
    public AdvanceFont() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LFont = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        LSize = new javax.swing.JList<>();
        JBApply = new javax.swing.JButton();
        BtCancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelFont = new javax.swing.JLabel();
        LabelSize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("   SET FONT");
        jLabel1.setOpaque(true);

        LFont.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LFont.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Arial", "Cambria", "Calibri", "Comic Sans MS", "Helvetica", "Times New Roman", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LFont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LFontMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(LFont);

        LSize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LSize.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "8", "10", "12", "14", "16", "18", "20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LSizeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(LSize);

        JBApply.setText("Apply");
        JBApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApplyActionPerformed(evt);
            }
        });

        BtCancel.setText("Cancel");
        BtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Font :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Size:");

        LabelFont.setBackground(new java.awt.Color(204, 255, 255));
        LabelFont.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelFont.setEnabled(false);
        LabelFont.setName("LabelFont"); // NOI18N
        LabelFont.setOpaque(true);

        LabelSize.setBackground(new java.awt.Color(204, 255, 255));
        LabelSize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LabelSize.setEnabled(false);
        LabelSize.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(JBApply)))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtCancel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addComponent(LabelSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelFont, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(LabelSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBApply)
                            .addComponent(BtCancel)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        LabelSize.getAccessibleContext().setAccessibleName("LabelSize");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApplyActionPerformed
        // TODO add your handling code here:
        switch (LFont.getSelectedValue()) {
            case "Times New Roman":
                Chat.jTextArea1.setFont(new Font("Times New Roman", Font.PLAIN, Integer.parseInt(LSize.getSelectedValue())));                
                break;
            case "Arial":
                Chat.jTextArea1.setFont(new Font("Arial", Font.PLAIN, Integer.parseInt(LSize.getSelectedValue())));
                break;
            case "Comic Sans MS":
                Chat.jTextArea1.setFont(new Font("Comic Sans MS", Font.PLAIN, Integer.parseInt(LSize.getSelectedValue())));
                break;
            case "Helvetica":
                Chat.jTextArea1.setFont(new Font("Helvetica", Font.PLAIN, Integer.parseInt(LSize.getSelectedValue())));
                break;
            case "Calibri":
                Chat.jTextArea1.setFont(new Font("Calibri", Font.PLAIN, Integer.parseInt(LSize.getSelectedValue())));
                break;
            case "Cambria":  
                Chat.jTextArea1.setFont(new Font("Cambria", Font.PLAIN, Integer.parseInt(LSize.getSelectedValue())));
                break;
            default:
                break;
        }
        this.dispose();

        
        
    }//GEN-LAST:event_JBApplyActionPerformed

    private void BtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtCancelActionPerformed

    private void LFontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LFontMouseClicked
        // TODO add your handling code here:
        LabelFont.setText(LFont.getSelectedValue());
    }//GEN-LAST:event_LFontMouseClicked

    private void LSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LSizeMouseClicked
        // TODO add your handling code here:
        LabelSize.setText(LSize.getSelectedValue());
    }//GEN-LAST:event_LSizeMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCancel;
    private javax.swing.JButton JBApply;
    private javax.swing.JList<String> LFont;
    private javax.swing.JList<String> LSize;
    private javax.swing.JLabel LabelFont;
    private javax.swing.JLabel LabelSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
